version: "3.8"
services:
  lensview-beta:
    image: lensview-beta-image:${DOCKER_VERSION_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 3000
    container_name: lensview-beta-container
    ports:
      - "3000:3000/tcp"
    env_file:
      - .env
