/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
const documents = {
    "\n  fragment AccountFields on Account {\n    owner\n    address\n    score\n    metadata {\n      ...AccountMetadata\n    }\n    username {\n      ...UsernameFields\n    }\n    operations {\n      ...LoggedInAccountOperationsFields\n    }\n  }\n": types.AccountFieldsFragmentDoc,
    "\n  fragment AccountMetadata on AccountMetadata {\n    id\n    name\n    bio\n    picture\n    coverPicture\n    attributes {\n      ...MetadataAttributeFields\n    }\n  }\n": types.AccountMetadataFragmentDoc,
    "\n  fragment LoggedInAccountOperationsFields on LoggedInAccountOperations {\n    id\n    isFollowedByMe\n    isFollowingMe\n    isMutedByMe\n    isBlockedByMe\n    hasBlockedMe\n    canBlock\n    canUnblock\n    hasReported\n  }\n": types.LoggedInAccountOperationsFieldsFragmentDoc,
    "\n  fragment UsernameFields on Username {\n    localName\n    linkedTo\n    ownedBy\n    value\n  }\n": types.UsernameFieldsFragmentDoc,
    "\n  fragment MetadataAttributeFields on MetadataAttribute {\n    type\n    key\n    value\n  }\n": types.MetadataAttributeFieldsFragmentDoc,
    "\n  fragment SelfFundedTransactionRequestFields on SelfFundedTransactionRequest {\n    reason\n    raw {\n      chainId\n      data\n      from\n      gasLimit\n      maxFeePerGas\n      maxPriorityFeePerGas\n      nonce\n      to\n      type\n      value\n    }\n  }\n": types.SelfFundedTransactionRequestFieldsFragmentDoc,
    "\n  fragment SponsoredTransactionRequestFields on SponsoredTransactionRequest {\n    reason\n    raw {\n      chainId\n      data\n      from\n      gasLimit\n      maxFeePerGas\n      maxPriorityFeePerGas\n      nonce\n      to\n      type\n      value\n      customData {\n        customSignature\n        factoryDeps\n        gasPerPubdata\n        paymasterParams {\n          paymaster\n          paymasterInput\n        }\n      }\n    }\n  }\n": types.SponsoredTransactionRequestFieldsFragmentDoc,
    "\n  mutation Authenticate($request: SignedAuthChallenge!) {\n    authenticate(request: $request) {\n      ... on AuthenticationTokens {\n        accessToken\n        idToken\n        refreshToken\n      }\n      ... on WrongSignerError {\n        reason\n      }\n      ... on ExpiredChallengeError {\n        reason\n      }\n      ... on ForbiddenError {\n        reason\n      }\n    }\n  }\n": types.AuthenticateDocument,
    "\n  mutation Challenge($request: ChallengeRequest!) {\n    challenge(request: $request) {\n      id\n      text\n    }\n  }\n": types.ChallengeDocument,
    "\n  mutation Follow($request: CreateFollowRequest!) {\n    follow(request: $request) {\n      ... on FollowResponse {\n        hash\n      }\n      ... on SelfFundedTransactionRequest {\n        reason\n        raw {\n          chainId\n          data\n          from\n          gasLimit\n          maxFeePerGas\n          maxPriorityFeePerGas\n          nonce\n          to\n          type\n          value\n        }\n      }\n      ... on SponsoredTransactionRequest {\n        reason\n        raw {\n          chainId\n          data\n          from\n          gasLimit\n          maxFeePerGas\n          maxPriorityFeePerGas\n          nonce\n          to\n          type\n          value\n          customData {\n            customSignature\n            factoryDeps\n            gasPerPubdata\n            paymasterParams {\n              paymaster\n              paymasterInput\n            }\n          }\n        }\n      }\n      ... on TransactionWillFail {\n        reason\n      }\n    }\n  }\n": types.FollowDocument,
    "\n  query AccountsAvailable($request: AccountsAvailableRequest!) {\n    accountsAvailable(request: $request) {\n      items {\n        ... on AccountManaged {\n          account {\n            owner\n            address\n            username {\n              value\n              id\n            }\n            metadata {\n              name\n              picture\n              id\n            }\n          }\n        }\n      }\n    }\n  }\n": types.AccountsAvailableDocument,
    "\n  query Comments($request: PostReferencesRequest!) {\n    postReferences(request: $request) {\n      items {\n        ... on Post {\n          id\n          slug\n          timestamp\n          author {\n            metadata {\n              picture\n              name\n            }\n            owner\n            username {\n              value\n            }\n            address\n          }\n          metadata {\n            ... on TextOnlyMetadata {\n              content\n              tags\n              attributes {\n                key\n                value\n              }\n            }\n            ... on ImageMetadata {\n              content\n              tags\n            }\n          }\n          stats {\n            comments\n            upvotes: reactions(request: { type: UPVOTE })\n            downvotes: reactions(request: { type: DOWNVOTE })\n          }\n          operations {\n            hasUpVoted: hasReacted(request: { type: UPVOTE })\n            hasDownVoted: hasReacted(request: { type: DOWNVOTE })\n          }\n          root {\n            id\n            slug\n          }\n        }\n      }\n    }\n  }\n": types.CommentsDocument,
    "\n  query LinkPost($request: PostRequest!) {\n    post(request: $request) {\n      ... on Post {\n        id\n        metadata {\n          ... on LinkMetadata {\n            sharingLink\n            attributes {\n              key\n              value\n            }\n          }\n        }\n        stats {\n          comments\n          upvotes: reactions(request: { type: UPVOTE })\n          downvotes: reactions(request: { type: DOWNVOTE })\n        }\n        operations {\n          hasUpVoted: hasReacted(request: { type: UPVOTE })\n          hasDownVoted: hasReacted(request: { type: DOWNVOTE })\n        }\n        timestamp\n        author {\n          username {\n            value\n          }\n        }\n        slug\n      }\n    }\n  }\n": types.LinkPostDocument,
    "\n  query ProfileId($request: AccountRequest!) {\n    account(request: $request) {\n      address\n    }\n  }\n": types.ProfileIdDocument,
    "\n  query Profile(\n    $accountRequest: AccountRequest!\n    $statsRequest: AccountStatsRequest!\n  ) {\n    account(request: $accountRequest) {\n      createdAt\n      username {\n        value\n        localName\n      }\n      metadata {\n        name\n        picture\n        coverPicture\n        bio\n      }\n      operations {\n        isFollowedByMe\n        isFollowingMe\n      }\n      owner\n      address\n    }\n    accountStats(request: $statsRequest) {\n      graphFollowStats {\n        followers\n        following\n      }\n      feedStats {\n        comments\n        posts\n        quotes\n        reacted\n        reactions\n        reposts\n      }\n    }\n  }\n": types.ProfileDocument,
    "\n  query TransactionStatus($request: TransactionStatusRequest!) {\n    transactionStatus(request: $request) {\n      ... on FinishedTransactionStatus {\n        blockTimestamp\n      }\n      ... on PendingTransactionStatus {\n        blockTimestamp\n      }\n      ... on NotIndexedYetStatus {\n        reason\n      }\n      ... on FailedTransactionStatus {\n        reason\n      }\n    }\n  }\n": types.TransactionStatusDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment AccountFields on Account {\n    owner\n    address\n    score\n    metadata {\n      ...AccountMetadata\n    }\n    username {\n      ...UsernameFields\n    }\n    operations {\n      ...LoggedInAccountOperationsFields\n    }\n  }\n"): (typeof documents)["\n  fragment AccountFields on Account {\n    owner\n    address\n    score\n    metadata {\n      ...AccountMetadata\n    }\n    username {\n      ...UsernameFields\n    }\n    operations {\n      ...LoggedInAccountOperationsFields\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment AccountMetadata on AccountMetadata {\n    id\n    name\n    bio\n    picture\n    coverPicture\n    attributes {\n      ...MetadataAttributeFields\n    }\n  }\n"): (typeof documents)["\n  fragment AccountMetadata on AccountMetadata {\n    id\n    name\n    bio\n    picture\n    coverPicture\n    attributes {\n      ...MetadataAttributeFields\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment LoggedInAccountOperationsFields on LoggedInAccountOperations {\n    id\n    isFollowedByMe\n    isFollowingMe\n    isMutedByMe\n    isBlockedByMe\n    hasBlockedMe\n    canBlock\n    canUnblock\n    hasReported\n  }\n"): (typeof documents)["\n  fragment LoggedInAccountOperationsFields on LoggedInAccountOperations {\n    id\n    isFollowedByMe\n    isFollowingMe\n    isMutedByMe\n    isBlockedByMe\n    hasBlockedMe\n    canBlock\n    canUnblock\n    hasReported\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment UsernameFields on Username {\n    localName\n    linkedTo\n    ownedBy\n    value\n  }\n"): (typeof documents)["\n  fragment UsernameFields on Username {\n    localName\n    linkedTo\n    ownedBy\n    value\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment MetadataAttributeFields on MetadataAttribute {\n    type\n    key\n    value\n  }\n"): (typeof documents)["\n  fragment MetadataAttributeFields on MetadataAttribute {\n    type\n    key\n    value\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment SelfFundedTransactionRequestFields on SelfFundedTransactionRequest {\n    reason\n    raw {\n      chainId\n      data\n      from\n      gasLimit\n      maxFeePerGas\n      maxPriorityFeePerGas\n      nonce\n      to\n      type\n      value\n    }\n  }\n"): (typeof documents)["\n  fragment SelfFundedTransactionRequestFields on SelfFundedTransactionRequest {\n    reason\n    raw {\n      chainId\n      data\n      from\n      gasLimit\n      maxFeePerGas\n      maxPriorityFeePerGas\n      nonce\n      to\n      type\n      value\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment SponsoredTransactionRequestFields on SponsoredTransactionRequest {\n    reason\n    raw {\n      chainId\n      data\n      from\n      gasLimit\n      maxFeePerGas\n      maxPriorityFeePerGas\n      nonce\n      to\n      type\n      value\n      customData {\n        customSignature\n        factoryDeps\n        gasPerPubdata\n        paymasterParams {\n          paymaster\n          paymasterInput\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment SponsoredTransactionRequestFields on SponsoredTransactionRequest {\n    reason\n    raw {\n      chainId\n      data\n      from\n      gasLimit\n      maxFeePerGas\n      maxPriorityFeePerGas\n      nonce\n      to\n      type\n      value\n      customData {\n        customSignature\n        factoryDeps\n        gasPerPubdata\n        paymasterParams {\n          paymaster\n          paymasterInput\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Authenticate($request: SignedAuthChallenge!) {\n    authenticate(request: $request) {\n      ... on AuthenticationTokens {\n        accessToken\n        idToken\n        refreshToken\n      }\n      ... on WrongSignerError {\n        reason\n      }\n      ... on ExpiredChallengeError {\n        reason\n      }\n      ... on ForbiddenError {\n        reason\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation Authenticate($request: SignedAuthChallenge!) {\n    authenticate(request: $request) {\n      ... on AuthenticationTokens {\n        accessToken\n        idToken\n        refreshToken\n      }\n      ... on WrongSignerError {\n        reason\n      }\n      ... on ExpiredChallengeError {\n        reason\n      }\n      ... on ForbiddenError {\n        reason\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Challenge($request: ChallengeRequest!) {\n    challenge(request: $request) {\n      id\n      text\n    }\n  }\n"): (typeof documents)["\n  mutation Challenge($request: ChallengeRequest!) {\n    challenge(request: $request) {\n      id\n      text\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Follow($request: CreateFollowRequest!) {\n    follow(request: $request) {\n      ... on FollowResponse {\n        hash\n      }\n      ... on SelfFundedTransactionRequest {\n        reason\n        raw {\n          chainId\n          data\n          from\n          gasLimit\n          maxFeePerGas\n          maxPriorityFeePerGas\n          nonce\n          to\n          type\n          value\n        }\n      }\n      ... on SponsoredTransactionRequest {\n        reason\n        raw {\n          chainId\n          data\n          from\n          gasLimit\n          maxFeePerGas\n          maxPriorityFeePerGas\n          nonce\n          to\n          type\n          value\n          customData {\n            customSignature\n            factoryDeps\n            gasPerPubdata\n            paymasterParams {\n              paymaster\n              paymasterInput\n            }\n          }\n        }\n      }\n      ... on TransactionWillFail {\n        reason\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation Follow($request: CreateFollowRequest!) {\n    follow(request: $request) {\n      ... on FollowResponse {\n        hash\n      }\n      ... on SelfFundedTransactionRequest {\n        reason\n        raw {\n          chainId\n          data\n          from\n          gasLimit\n          maxFeePerGas\n          maxPriorityFeePerGas\n          nonce\n          to\n          type\n          value\n        }\n      }\n      ... on SponsoredTransactionRequest {\n        reason\n        raw {\n          chainId\n          data\n          from\n          gasLimit\n          maxFeePerGas\n          maxPriorityFeePerGas\n          nonce\n          to\n          type\n          value\n          customData {\n            customSignature\n            factoryDeps\n            gasPerPubdata\n            paymasterParams {\n              paymaster\n              paymasterInput\n            }\n          }\n        }\n      }\n      ... on TransactionWillFail {\n        reason\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AccountsAvailable($request: AccountsAvailableRequest!) {\n    accountsAvailable(request: $request) {\n      items {\n        ... on AccountManaged {\n          account {\n            owner\n            address\n            username {\n              value\n              id\n            }\n            metadata {\n              name\n              picture\n              id\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query AccountsAvailable($request: AccountsAvailableRequest!) {\n    accountsAvailable(request: $request) {\n      items {\n        ... on AccountManaged {\n          account {\n            owner\n            address\n            username {\n              value\n              id\n            }\n            metadata {\n              name\n              picture\n              id\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Comments($request: PostReferencesRequest!) {\n    postReferences(request: $request) {\n      items {\n        ... on Post {\n          id\n          slug\n          timestamp\n          author {\n            metadata {\n              picture\n              name\n            }\n            owner\n            username {\n              value\n            }\n            address\n          }\n          metadata {\n            ... on TextOnlyMetadata {\n              content\n              tags\n              attributes {\n                key\n                value\n              }\n            }\n            ... on ImageMetadata {\n              content\n              tags\n            }\n          }\n          stats {\n            comments\n            upvotes: reactions(request: { type: UPVOTE })\n            downvotes: reactions(request: { type: DOWNVOTE })\n          }\n          operations {\n            hasUpVoted: hasReacted(request: { type: UPVOTE })\n            hasDownVoted: hasReacted(request: { type: DOWNVOTE })\n          }\n          root {\n            id\n            slug\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query Comments($request: PostReferencesRequest!) {\n    postReferences(request: $request) {\n      items {\n        ... on Post {\n          id\n          slug\n          timestamp\n          author {\n            metadata {\n              picture\n              name\n            }\n            owner\n            username {\n              value\n            }\n            address\n          }\n          metadata {\n            ... on TextOnlyMetadata {\n              content\n              tags\n              attributes {\n                key\n                value\n              }\n            }\n            ... on ImageMetadata {\n              content\n              tags\n            }\n          }\n          stats {\n            comments\n            upvotes: reactions(request: { type: UPVOTE })\n            downvotes: reactions(request: { type: DOWNVOTE })\n          }\n          operations {\n            hasUpVoted: hasReacted(request: { type: UPVOTE })\n            hasDownVoted: hasReacted(request: { type: DOWNVOTE })\n          }\n          root {\n            id\n            slug\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query LinkPost($request: PostRequest!) {\n    post(request: $request) {\n      ... on Post {\n        id\n        metadata {\n          ... on LinkMetadata {\n            sharingLink\n            attributes {\n              key\n              value\n            }\n          }\n        }\n        stats {\n          comments\n          upvotes: reactions(request: { type: UPVOTE })\n          downvotes: reactions(request: { type: DOWNVOTE })\n        }\n        operations {\n          hasUpVoted: hasReacted(request: { type: UPVOTE })\n          hasDownVoted: hasReacted(request: { type: DOWNVOTE })\n        }\n        timestamp\n        author {\n          username {\n            value\n          }\n        }\n        slug\n      }\n    }\n  }\n"): (typeof documents)["\n  query LinkPost($request: PostRequest!) {\n    post(request: $request) {\n      ... on Post {\n        id\n        metadata {\n          ... on LinkMetadata {\n            sharingLink\n            attributes {\n              key\n              value\n            }\n          }\n        }\n        stats {\n          comments\n          upvotes: reactions(request: { type: UPVOTE })\n          downvotes: reactions(request: { type: DOWNVOTE })\n        }\n        operations {\n          hasUpVoted: hasReacted(request: { type: UPVOTE })\n          hasDownVoted: hasReacted(request: { type: DOWNVOTE })\n        }\n        timestamp\n        author {\n          username {\n            value\n          }\n        }\n        slug\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProfileId($request: AccountRequest!) {\n    account(request: $request) {\n      address\n    }\n  }\n"): (typeof documents)["\n  query ProfileId($request: AccountRequest!) {\n    account(request: $request) {\n      address\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Profile(\n    $accountRequest: AccountRequest!\n    $statsRequest: AccountStatsRequest!\n  ) {\n    account(request: $accountRequest) {\n      createdAt\n      username {\n        value\n        localName\n      }\n      metadata {\n        name\n        picture\n        coverPicture\n        bio\n      }\n      operations {\n        isFollowedByMe\n        isFollowingMe\n      }\n      owner\n      address\n    }\n    accountStats(request: $statsRequest) {\n      graphFollowStats {\n        followers\n        following\n      }\n      feedStats {\n        comments\n        posts\n        quotes\n        reacted\n        reactions\n        reposts\n      }\n    }\n  }\n"): (typeof documents)["\n  query Profile(\n    $accountRequest: AccountRequest!\n    $statsRequest: AccountStatsRequest!\n  ) {\n    account(request: $accountRequest) {\n      createdAt\n      username {\n        value\n        localName\n      }\n      metadata {\n        name\n        picture\n        coverPicture\n        bio\n      }\n      operations {\n        isFollowedByMe\n        isFollowingMe\n      }\n      owner\n      address\n    }\n    accountStats(request: $statsRequest) {\n      graphFollowStats {\n        followers\n        following\n      }\n      feedStats {\n        comments\n        posts\n        quotes\n        reacted\n        reactions\n        reposts\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query TransactionStatus($request: TransactionStatusRequest!) {\n    transactionStatus(request: $request) {\n      ... on FinishedTransactionStatus {\n        blockTimestamp\n      }\n      ... on PendingTransactionStatus {\n        blockTimestamp\n      }\n      ... on NotIndexedYetStatus {\n        reason\n      }\n      ... on FailedTransactionStatus {\n        reason\n      }\n    }\n  }\n"): (typeof documents)["\n  query TransactionStatus($request: TransactionStatusRequest!) {\n    transactionStatus(request: $request) {\n      ... on FinishedTransactionStatus {\n        blockTimestamp\n      }\n      ... on PendingTransactionStatus {\n        blockTimestamp\n      }\n      ... on NotIndexedYetStatus {\n        reason\n      }\n      ... on FailedTransactionStatus {\n        reason\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;
